# Generated by Django 5.1.2 on 2025-04-16 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('games_played', models.IntegerField(default=0)),
                ('average_points', models.FloatField(default=0)),
                ('average_assists', models.FloatField(default=0)),
                ('average_blocks', models.FloatField(default=0)),
                ('average_aces', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaapp.player')),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
    ]
