# Generated by Django 5.1.2 on 2025-04-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0002_playerseasonstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
